arch:
    - arm64

services:
    - docker

before_install:
    - docker build -t express .

script:
    - docker run -p 8080:8080 express& #run the container in background
    - sleep 30; curl 127.0.0.1:8080/user/KarolPlonka

